/**
 * Route registry — spec 004 AC-7. `GET /api/v1/openapi.json` (app/api/v1/openapi.json/route.ts)
 * generates its document from this list rather than a hand-written JSON file, and
 * `scripts/check-openapi-drift.ts` fails CI if a `route.ts` file under `app/api/v1/` exports an
 * HTTP method not listed here (or vice versa) — the two are required to stay in sync.
 *
 * Every domain spec (005 onward) that adds a route must add its entry here in the same PR.
 */
export interface OpenApiRouteEntry {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  /** OpenAPI-style path, e.g. `/health` or `/requests/{id}` — relative to `/api/v1`. */
  path: string;
  summary: string;
  tags: string[];
}

export const OPENAPI_ROUTES: OpenApiRouteEntry[] = [
  { method: 'GET', path: '/health', summary: 'Liveness/readiness check', tags: ['foundation'] },
  { method: 'GET', path: '/openapi.json', summary: 'Generated OpenAPI 3.x document', tags: ['foundation'] },
  { method: 'POST', path: '/auth/otp/request', summary: 'Request a phone OTP', tags: ['auth'] },
  { method: 'POST', path: '/auth/otp/verify', summary: 'Verify a phone OTP and establish a session', tags: ['auth'] },
  { method: 'POST', path: '/auth/register', summary: 'Register with email + password', tags: ['auth'] },
  { method: 'POST', path: '/auth/login', summary: 'Log in with email + password', tags: ['auth'] },
  { method: 'POST', path: '/auth/oauth/google', summary: 'Complete Google OAuth login', tags: ['auth'] },
  { method: 'POST', path: '/auth/oauth/apple', summary: 'Complete Apple OAuth login', tags: ['auth'] },
  { method: 'POST', path: '/auth/mfa/verify', summary: 'Complete an MFA-pending admin login', tags: ['auth'] },
  { method: 'POST', path: '/auth/logout', summary: 'Invalidate the current session', tags: ['auth'] },
  { method: 'POST', path: '/auth/step-up', summary: 'Issue a step-up token for a sensitive action', tags: ['auth'] },
  { method: 'GET', path: '/users/me', summary: 'Current user: profiles and session active mode', tags: ['users'] },
  {
    method: 'POST',
    path: '/users/me/provider-profile',
    summary: 'Become a provider (idempotent; does not switch mode)',
    tags: ['users'],
  },
  {
    method: 'PATCH',
    path: '/users/me/active-mode',
    summary: 'Switch the current session between customer/provider mode',
    tags: ['users'],
  },
  { method: 'GET', path: '/users/me/sessions', summary: "List the caller's own active sessions", tags: ['privacy'] },
  {
    method: 'DELETE',
    path: '/users/me/sessions/{id}',
    summary: 'Log out a single device (must belong to the caller)',
    tags: ['privacy'],
  },
  {
    method: 'DELETE',
    path: '/users/me/sessions',
    summary: 'Log out all other devices (current session survives); requires step-up',
    tags: ['privacy'],
  },
  {
    method: 'POST',
    path: '/users/me/data-export',
    summary: 'Request an asynchronous export of permitted personal data; requires step-up',
    tags: ['privacy'],
  },
  {
    method: 'GET',
    path: '/users/me/data-export/{id}',
    summary: 'Data export request status (and signed download URL once ready)',
    tags: ['privacy'],
  },
  {
    method: 'GET',
    path: '/users/me/data-export/{id}/download',
    summary: 'Signed, time-limited download of a ready data export',
    tags: ['privacy'],
  },
  {
    method: 'GET',
    path: '/users/me/deletion',
    summary: "Current account lifecycle status and pending deletion's grace-period end (if any)",
    tags: ['privacy'],
  },
  {
    method: 'POST',
    path: '/users/me/deletion',
    summary: 'Request account deletion (grace period; blocked by an active booking); requires step-up',
    tags: ['privacy'],
  },
  {
    method: 'POST',
    path: '/users/me/deletion/cancel',
    summary: "Cancel the caller's own pending deletion within the grace period",
    tags: ['privacy'],
  },
  { method: 'GET', path: '/users/me/mfa', summary: 'Current Security Center MFA on/off state', tags: ['privacy'] },
  {
    method: 'PATCH',
    path: '/users/me/mfa',
    summary: 'Toggle the Security Center MFA on/off control; requires step-up',
    tags: ['privacy'],
  },
  { method: 'GET', path: '/admin/roles', summary: 'List the seven canonical admin roles; Super Admin only', tags: ['admin-rbac'] },
  {
    method: 'POST',
    path: '/admin/users/{userId}/roles',
    summary: 'Assign an admin role to a user; Super Admin only, audited',
    tags: ['admin-rbac'],
  },
  {
    method: 'DELETE',
    path: '/admin/users/{userId}/roles/{role}',
    summary: 'Revoke an admin role from a user; Super Admin only, blocks the last remaining super_admin',
    tags: ['admin-rbac'],
  },
  {
    method: 'POST',
    path: '/admin/approvals/{actionId}/approve',
    summary: 'Approve a pending high/critical-risk AdminAction (second, distinct, authorized admin)',
    tags: ['admin-rbac'],
  },
  {
    method: 'POST',
    path: '/admin/approvals/{actionId}/reject',
    summary: 'Reject a pending high/critical-risk AdminAction',
    tags: ['admin-rbac'],
  },
  {
    method: 'GET',
    path: '/admin/approvals/pending',
    summary: "Pending AdminActions the caller is authorized to decide, scoped to their role(s)",
    tags: ['admin-rbac'],
  },
  {
    method: 'POST',
    path: '/admin/actions/{actionId}/post-action-review',
    summary: 'Record the mandatory post-action review for an emergency-bypassed AdminAction',
    tags: ['admin-rbac'],
  },
  {
    method: 'GET',
    path: '/admin/actions/pending-review',
    summary: 'AdminActions awaiting mandatory post-action review, scoped to the caller',
    tags: ['admin-rbac'],
  },
  { method: 'GET', path: '/categories', summary: 'List published categories (public)', tags: ['catalog'] },
  { method: 'GET', path: '/categories/{id}', summary: 'Published category detail, with published child subcategories (public)', tags: ['catalog'] },
  { method: 'GET', path: '/services/{id}', summary: 'Published service detail (public)', tags: ['catalog'] },
  { method: 'GET', path: '/admin/categories', summary: 'List all categories, any status; Content/Marketplace admin', tags: ['catalog'] },
  { method: 'GET', path: '/admin/categories/{id}', summary: 'Category detail, any status; Content/Marketplace admin', tags: ['catalog'] },
  { method: 'POST', path: '/admin/categories', summary: 'Create a category; Content/Marketplace admin', tags: ['catalog'] },
  { method: 'PATCH', path: '/admin/categories/{id}', summary: 'Edit a category (optimistic concurrency); Content/Marketplace admin', tags: ['catalog'] },
  { method: 'POST', path: '/admin/categories/{id}/retire', summary: 'Retire a category; blocked while active services remain attached', tags: ['catalog'] },
  { method: 'GET', path: '/admin/categories/{categoryId}/subcategories', summary: 'List subcategories under a category, any status; Content/Marketplace admin', tags: ['catalog'] },
  { method: 'POST', path: '/admin/categories/{categoryId}/subcategories', summary: 'Create a subcategory under an active category', tags: ['catalog'] },
  { method: 'GET', path: '/admin/subcategories/{id}', summary: 'Subcategory detail, any status; Content/Marketplace admin', tags: ['catalog'] },
  { method: 'PATCH', path: '/admin/subcategories/{id}', summary: 'Edit a subcategory (optimistic concurrency); Content/Marketplace admin', tags: ['catalog'] },
  { method: 'POST', path: '/admin/subcategories/{id}/retire', summary: 'Retire a subcategory; blocked while active services remain attached', tags: ['catalog'] },
  { method: 'GET', path: '/admin/services/{id}', summary: 'Service detail, any status; Content/Marketplace admin', tags: ['catalog'] },
  { method: 'POST', path: '/admin/services', summary: 'Create a service under a valid taxonomy path', tags: ['catalog'] },
  { method: 'PATCH', path: '/admin/services/{id}', summary: 'Edit a service (optimistic concurrency); Content/Marketplace admin', tags: ['catalog'] },
  { method: 'POST', path: '/admin/services/{id}/retire', summary: 'Retire a service (soft lifecycle change, not delete)', tags: ['catalog'] },
  { method: 'POST', path: '/admin/catalog/suggestions', summary: "Submit an AI catalog suggestion (spec 034); always pending_review, never mutates a catalog entity", tags: ['catalog'] },
  { method: 'GET', path: '/admin/catalog/pending-review', summary: 'List pending AI catalog suggestions; Content/Marketplace admin', tags: ['catalog'] },
  { method: 'POST', path: '/admin/catalog/pending-review/{id}/approve', summary: 'Approve a suggestion — creates the entity pending_review, never publishes directly', tags: ['catalog'] },
  { method: 'POST', path: '/admin/catalog/pending-review/{id}/reject', summary: 'Reject a suggestion — records reviewer/time, publishes nothing', tags: ['catalog'] },
  { method: 'GET', path: '/categories/{id}/page', summary: 'Aggregated category page data (public)', tags: ['service-page'] },
  { method: 'GET', path: '/services/{id}/page', summary: 'Aggregated service page data: fields, FAQs, packages, pricing (public)', tags: ['service-page'] },
  { method: 'GET', path: '/services/{id}/fields', summary: 'Field definitions consumed identically by the manual form and the AI (spec 034)', tags: ['service-page'] },
  { method: 'POST', path: '/admin/services/{id}/fields', summary: 'Define a service field; Content/Marketplace admin', tags: ['service-page'] },
  { method: 'POST', path: '/admin/services/{id}/faqs', summary: 'Add an official FAQ, published immediately; Content/Marketplace admin', tags: ['service-page'] },
  { method: 'POST', path: '/providers/me/services/{id}/faqs', summary: "Add the caller's own FAQ for a service they offer; session (provider, ownership-checked)", tags: ['service-page'] },
  {
    method: 'POST',
    path: '/admin/services/{id}/faqs/ai-suggestions/{suggestionId}/approve',
    summary: 'Publish an AI-drafted FAQ suggestion; Content/Marketplace admin, AI never publishes directly',
    tags: ['service-page'],
  },
  { method: 'POST', path: '/location/geocode', summary: 'Resolve address text to coordinates + hierarchy; session or guest', tags: ['location'] },
  { method: 'POST', path: '/location/reverse-geocode', summary: 'Resolve coordinates to an address; session or guest', tags: ['location'] },
  { method: 'GET', path: '/addresses', summary: "List the caller's own saved addresses", tags: ['location'] },
  { method: 'POST', path: '/addresses', summary: 'Save a new address for the caller', tags: ['location'] },
  { method: 'PATCH', path: '/addresses/{id}', summary: 'Update a saved address; owner only', tags: ['location'] },
  { method: 'DELETE', path: '/addresses/{id}', summary: 'Delete a saved address; owner only, blocked while a booking references it', tags: ['location'] },
  {
    method: 'GET',
    path: '/providers/{id}/service-area-check',
    summary: "Whether a candidate location falls within a provider's declared service area; session or guest",
    tags: ['location'],
  },
  { method: 'GET', path: '/home', summary: 'Customer-mode home feed (curated/recent/active-booking); session or guest', tags: ['home'] },
  {
    method: 'GET',
    path: '/users/me/personalization-settings',
    summary: "Current home-feed personalization opt-in/out state",
    tags: ['home'],
  },
  {
    method: 'PATCH',
    path: '/users/me/personalization-settings',
    summary: 'Opt out of/adjust home-feed personalization',
    tags: ['home'],
  },
  { method: 'GET', path: '/search', summary: 'Authoritative, paginated search results; session or guest', tags: ['search'] },
  {
    method: 'POST',
    path: '/search/interpret',
    summary: 'AI-assisted NL/voice-transcribed text -> structured search intent (never results); session or guest',
    tags: ['search'],
  },
  { method: 'GET', path: '/search/autocomplete', summary: 'Search suggestions; session or guest', tags: ['search'] },
  { method: 'POST', path: '/search/recent', summary: "Record a search to the caller's own recent-searches list", tags: ['search'] },
  // Spec 015 §3 — request creation & lifecycle.
  {
    method: 'POST',
    path: '/requests',
    summary: 'Create (draft -> submitted) a service request; requires Idempotency-Key',
    tags: ['requests'],
  },
  { method: 'GET', path: '/requests', summary: "List the caller's own requests (active|history)", tags: ['requests'] },
  { method: 'GET', path: '/requests/{id}', summary: "Read one of the caller's own requests", tags: ['requests'] },
  {
    method: 'GET',
    path: '/requests/{id}/cancel-preview',
    summary: 'Dry run: the consequence of cancelling, shown before confirmation',
    tags: ['requests'],
  },
  {
    method: 'POST',
    path: '/requests/{id}/cancel',
    summary: 'Cancel a request before provider selection',
    tags: ['requests'],
  },
  // Spec 016 §3 — provider availability & service areas. `/providers/{id}/availability` is the
  // only one of these a non-owner may call; everything under `/providers/me/**` is owner-only and
  // resolves the provider from the session, never from a client-supplied id.
  {
    method: 'GET',
    path: '/providers/{id}/availability',
    summary: 'Simplified customer-facing availability state and reason; session or guest',
    tags: ['availability'],
  },
  {
    method: 'POST',
    path: '/providers/{id}/availability-notify',
    summary: 'Opt in to be notified when an unavailable provider is free again; session (customer)',
    tags: ['availability'],
  },
  {
    method: 'GET',
    path: '/providers/me/availability/schedule',
    summary: "The caller's own weekly recurring schedule and scheduling timezone; session (provider)",
    tags: ['availability'],
  },
  {
    method: 'PUT',
    path: '/providers/me/availability/schedule',
    summary: 'Replace the weekly recurring schedule in one transaction; session (provider)',
    tags: ['availability'],
  },
  {
    method: 'GET',
    path: '/providers/me/availability/overrides',
    summary: 'Date-specific availability overrides in a date range; session (provider)',
    tags: ['availability'],
  },
  {
    method: 'POST',
    path: '/providers/me/availability/overrides',
    summary: 'Create a date-specific override; session (provider)',
    tags: ['availability'],
  },
  {
    method: 'PUT',
    path: '/providers/me/availability/overrides/{date}',
    summary: 'Update the override for a date; session (provider)',
    tags: ['availability'],
  },
  {
    method: 'DELETE',
    path: '/providers/me/availability/overrides/{date}',
    summary: "Remove a date's override, restoring the weekly pattern; session (provider)",
    tags: ['availability'],
  },
  {
    method: 'GET',
    path: '/providers/me/availability/slots',
    summary: 'Buffer-aware bookable slots for a service over a date range; session (provider), owner-only detail',
    tags: ['availability'],
  },
  {
    method: 'GET',
    path: '/providers/me/service-areas',
    summary: "The caller's own service-area configuration; session (provider)",
    tags: ['availability'],
  },
  {
    method: 'PUT',
    path: '/providers/me/service-areas',
    summary: 'Replace the whole service-area configuration in one transaction; session (provider)',
    tags: ['availability'],
  },
  // Spec 017 §3 — provider matching, ranking & distribution.
  {
    method: 'GET',
    path: '/requests/{id}/matches',
    summary: 'Admin-only ranking explainability: who was excluded/ranked and why (AC-6)',
    tags: ['matching'],
  },
  {
    method: 'GET',
    path: '/providers/me/requests',
    summary: "The caller's own distributed-to inbox; session (provider)",
    tags: ['matching'],
  },
  {
    method: 'GET',
    path: '/providers/me/requests/{id}',
    summary: 'One distributed request, with its available action; session (provider), distributed-to-only',
    tags: ['matching'],
  },
  {
    method: 'POST',
    path: '/providers/me/requests/{id}/accept',
    summary: 'Accept a distributed request (fixed/package/hourly only); enforces the single-claim invariant',
    tags: ['matching'],
  },
  {
    method: 'POST',
    path: '/providers/me/requests/{id}/decline',
    summary: 'Decline a distributed request; always available while actionable',
    tags: ['matching'],
  },
  {
    method: 'PATCH',
    path: '/admin/services/{id}/matching-weights',
    summary: 'Configure a service\'s ranking-weight/pool-size override; admin, risk-tier medium',
    tags: ['matching'],
  },
  {
    method: 'GET',
    path: '/admin/matching/suggestions',
    summary: 'List AI-proposed ranking-weight suggestions pending admin review (AC-7)',
    tags: ['matching'],
  },
  {
    method: 'POST',
    path: '/admin/matching/suggestions/{id}/approve',
    summary: "Approve a suggestion — applies its weights to the target service; admin, risk-tier medium",
    tags: ['matching'],
  },
  {
    method: 'POST',
    path: '/admin/matching/suggestions/{id}/reject',
    summary: 'Reject a suggestion — never applied; admin, risk-tier medium',
    tags: ['matching'],
  },
];
